inputs:
  prefix:
    description: 'Install prefix'
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Cache GRPC build
      id: grpc-build
      uses: actions/cache@v3
      with:
        path: ${{ inputs.prefix }}
        key: grpc-v1.52.1

    - name: Download GRPC
      if: steps.grpc-build.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: grpc/grpc
        ref: v1.52.1
        path: ${{ inputs.prefix }}
        submodules: true

    - name: Build GRPC
      if: steps.grpc-build.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.prefix }}
      shell: bash
      run: |
        mkdir build -p
        cd build
        cmake .. -DgRPC_INSTALL=ON 
        make

    - name: Install GRPC
      working-directory: ${{ inputs.prefix }}/build
      shell: bash
      run: |
        sudo make install