name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  gcc_build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Install gcc
        run: |
          sudo apt update
          sudo apt install gcc-11 g++-11
        shell: bash

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential autoconf libtool pkg-config
        shell: bash

      - name: Cache GRPC build
        id: grpc-build
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/external/grpc/
          key: grpc-v1.52.1

      - name: Download GRPC
        if: steps.grpc-build.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: grpc/grpc
          ref: v1.52.1
          path: ${{github.workspace}}/external/grpc
          submodules: true

      - name: Build GRPC
        if: steps.grpc-build.outputs.cache-hit != 'true'
        working-directory: ${{github.workspace}}/external/grpc
        run: |
          mkdir build -p
          cd build
          cmake .. -DgRPC_INSTALL=ON 
          make

      - name: Install GRPC
        working-directory: ${{github.workspace}}/external/grpc/build
        run: |
          sudo make install     

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release
        env:
          CC:   gcc-11
          CXX:  g++-11

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release

  clang_build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install clang
        run: |
          sudo apt update
          sudo apt install clang-13
        shell: bash

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential autoconf libtool pkg-config
        shell: bash

      - name: Cache GRPC build
        id: grpc-build
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/external/grpc/
          key: grpc-v1.52.1

      - name: Download GRPC
        if: steps.grpc-build.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: grpc/grpc
          ref: v1.52.1
          path: ${{github.workspace}}/external/grpc
          submodules: true

      - name: Build GRPC
        if: steps.grpc-build.outputs.cache-hit != 'true'
        working-directory: ${{github.workspace}}/external/grpc
        run: |
          mkdir build -p
          cd build
          cmake .. -DgRPC_INSTALL=ON 
          make

      - name: Install GRPC
        working-directory: ${{github.workspace}}/external/grpc/build
        run: |
          sudo make install     

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release
        env:
          CC:   clang-13
          CXX:  clang++-13

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release